apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: Example application to import into Backstage.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: aardvaaark
